### PR TITLE
Add ja translate

### PR DESCRIPTION
**Pull request by shg166**
Japanese translation files have been added.
Updated information is still in English to avoid mistakes.

### CODE REVIEW

**Comment by algernon-A** [comment]
Just holding this one prior to a new control being added which will require an additional translation - will let you know when ready.

**Comment by shg166** [comment]
Thank you for your reply.
Please notify me when you know the schedule.
I will translate as soon as I am notified.

**Comment by algernon-A** [comment]
Have just pushed the updated en.xml translation file: note the two new keys :
ZMD_PNL_DIS
ZMD_PNL_DIS_TIP

**Comment by shg166** [comment]
Thank you, I've updated the translation content that was added.
I'd like to support other mods in Japanese as well.
Can I make a pull request for each mod?

**Comment by algernon-A** [comment]
Yes, pull requests for other mods are most welcome, thanks!

**Comment by shg166** [comment]
Thank you.
I'll make a pull request when I'm ready.

**Pull request merged**
